import { Flight, Hotel, Room, Tour, Visa, Booking, HotelReview, Profile, SavedItem } from "./types/database";

export const AIRPORTS = [
  { code: "DAC", name: "Hazrat Shahjalal Intl", city: "Dhaka", country: "Bangladesh" },
  { code: "CXB", name: "Cox's Bazar Airport", city: "Cox's Bazar", country: "Bangladesh" },
  { code: "CGP", name: "Shah Amanat Intl", city: "Chittagong", country: "Bangladesh" },
  { code: "ZYL", name: "Osmani Intl Airport", city: "Sylhet", country: "Bangladesh" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { code: "DXB", name: "Dubai Intl Airport", city: "Dubai", country: "UAE" },
  { code: "JED", name: "King Abdulaziz Intl", city: "Jeddah", country: "Saudi Arabia" },
  { code: "KUL", name: "Kuala Lumpur Intl", city: "Kuala Lumpur", country: "Malaysia" },
  { code: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom" },
];

export const MOCK_PROFILE: Profile = {
  id: "",
  email: "",
  phone: "",
  display_name: "",
  photo_url: "",
  gender: "",
  present_address: "",
  permanent_address: "",
  marital_status: "",
  date_of_birth: "",
  passport_country: "",
  passport_number: "",
  passport_expiry: "",
  national_id: "",
  nationality: "",
  emergency_contact: "",
  religion: "",
  language_preference: "English",
  role: "user",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "fl-1",
    trip_type: "oneway",
    segments: [
      {
        from: "Dhaka (DAC)",
        to: "Cox's Bazar (CXB)",
        departure_date: "2026-08-10",
        departure_time: "08:30 AM",
        arrival_time: "09:35 AM",
        duration: "1h 05m",
      },
    ],
    airline: "Biman Bangladesh",
    flight_number: "BG-433",
    price: 4800,
    currency: "BDT",
    class: "economy",
    available_seats: 14,
    max_travelers: 9,
    stops: 0,
    logo_url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=120&q=80",
  },
  {
    id: "fl-2",
    trip_type: "roundtrip",
    segments: [
      {
        from: "Dhaka (DAC)",
        to: "Bangkok (BKK)",
        departure_date: "2026-08-15",
        return_date: "2026-08-22",
        departure_time: "11:45 AM",
        arrival_time: "03:15 PM",
        duration: "2h 30m",
      },
    ],
    airline: "US-Bangla Airlines",
    flight_number: "BS-217",
    price: 28500,
    currency: "BDT",
    class: "economy",
    available_seats: 8,
    max_travelers: 9,
    stops: 0,
    logo_url: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=120&q=80",
  },
  {
    id: "fl-3",
    trip_type: "roundtrip",
    segments: [
      {
        from: "Dhaka (DAC)",
        to: "Dubai (DXB)",
        departure_date: "2026-09-01",
        return_date: "2026-09-10",
        departure_time: "07:15 PM",
        arrival_time: "10:45 PM",
        duration: "5h 30m",
      },
    ],
    airline: "Emirates",
    flight_number: "EK-585",
    price: 64500,
    currency: "BDT",
    class: "business",
    available_seats: 22,
    max_travelers: 9,
    stops: 0,
    logo_url: "https://images.unsplash.com/photo-1508672019048-805479760c23?auto=format&fit=crop&w=120&q=80",
  },
];

export const MOCK_HOTELS: Hotel[] = [
  {
    id: "ht-1",
    name: "Ocean Paradise Hotel & Resort",
    city: "Cox's Bazar",
    area: "Kolatoli Beach",
    address: "28-29 Hotel Motel Zone, Kolatoli, Cox's Bazar",
    star_rating: 5,
    description: "Experience luxurious beachfront living at Cox's Bazar premier resort with infinity pool, ocean-view suites, and fine dining restaurants.",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
    ],
    facilities: {
      Business: ["Business Center", "Meeting Rooms", "High-speed Internet"],
      Fitness: ["Gymnasium", "Yoga Studio"],
      Food: ["Buffet Breakfast", "Beachside Seafood Grill", "24/7 Room Service"],
      General: ["Free Wi-Fi", "24-hour Front Desk", "Elevator", "Air Conditioning"],
      "Indoor Entertainment": ["Billiards", "Kids Play Area"],
      Media: ["Flat-screen TV", "Satellite Channels"],
      Parking: ["Free On-site Valet Parking"],
      Safety: ["Fire Extinguishers", "CCTV in Common Areas", "24/7 Security"],
      Services: ["Airport Shuttle", "Car Rental", "Laundry Service"],
      Transportation: ["Private Car Booking", "Beach Buggy Service"],
    },
    policies: {
      check_in_time: "02:00 PM",
      check_out_time: "12:00 PM",
      special_instructions: "Valid NID or Passport required during check-in.",
      child_policy: "Children under 5 stay free using existing bedding.",
      pet_policy: "Pets are not allowed.",
      house_rules: ["No smoking inside rooms", "Pool hours: 7:00 AM - 9:00 PM"],
    },
    discount: 15,
    latitude: 21.4172,
    longitude: 91.9804,
    min_price: 6500,
    rooms_count: 4,
    nearby: [
      { name: "Kolatoli Beach", type: "Beach", distance: "0.2 km" },
      { name: "Sugandha Beach Market", type: "Shopping", distance: "0.8 km" },
      { name: "Radiant Fish World", type: "Attraction", distance: "2.1 km" },
    ],
  },
  {
    id: "ht-2",
    name: "Grand Palace Hotel & Resort Sylhet",
    city: "Sylhet",
    area: "Jalalabad",
    address: "Jalalabad, Sylhet 3100, Bangladesh",
    star_rating: 4,
    description: "Nestled amidst lush green tea gardens, Grand Palace Sylhet offers world-class hospitality, mountain views, and quiet luxury.",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
    ],
    facilities: {
      General: ["Free Wi-Fi", "Conference Rooms", "Garden"],
      Food: ["Multi-Cuisine Restaurant", "Tea Lounge"],
      Fitness: ["Outdoor Pool", "Gym"],
      Parking: ["Free Parking"],
      Services: ["Concierge Desk"],
    },
    policies: {
      check_in_time: "01:00 PM",
      check_out_time: "11:30 AM",
      special_instructions: "Marriage certificate required for local Bangladeshi couples.",
      child_policy: "Kids below 8 stay free.",
      pet_policy: "Not allowed.",
      house_rules: ["Quiet hours after 10 PM"],
    },
    discount: 10,
    latitude: 24.8949,
    longitude: 91.8687,
    min_price: 5200,
    rooms_count: 3,
    nearby: [
      { name: "Hazrat Shah Jalal Shrine", type: "Heritage", distance: "1.5 km" },
      { name: "Lakkatura Tea Garden", type: "Nature", distance: "3.2 km" },
    ],
  },
  {
    id: "ht-3",
    name: "The Westin Dhaka",
    city: "Dhaka",
    area: "Gulshan 2",
    address: "Main Gulshan Avenue, Plot-01, Road 45, Dhaka 1212",
    star_rating: 5,
    description: "Located in the heart of Dhaka business district Gulshan, featuring Heavenly Beds, 5-star international dining, and state of the art spa.",
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80",
    ],
    facilities: {
      Business: ["Business Center", "Executive Lounge"],
      Food: ["Seasonal Tastes", "Prego Italian Restaurant", "Daily Treats"],
      Fitness: ["Heavenly Spa", "Heated Pool", "WestinWORKOUT Gym"],
      Services: ["Limousine Service", "Airport Shuttle"],
    },
    policies: {
      check_in_time: "03:00 PM",
      check_out_time: "12:00 PM",
    },
    discount: 5,
    latitude: 23.7937,
    longitude: 90.4137,
    min_price: 18500,
    rooms_count: 5,
    nearby: [
      { name: "Gulshan Lake Park", type: "Park", distance: "0.4 km" },
      { name: "Jamuna Future Park", type: "Shopping Mall", distance: "4.0 km" },
    ],
  },
];

export const MOCK_ROOMS: Room[] = [
  {
    id: "rm-1",
    hotel_id: "ht-1",
    room_type: "Deluxe Ocean View King",
    price_per_night: 7500,
    available_count: 5,
    max_adults: 2,
    max_children: 1,
    features: ["Private Balcony", "Sea View", "King Bed", "Free Breakfast", "Free Wi-Fi", "42-inch Smart TV"],
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80"],
  },
  {
    id: "rm-2",
    hotel_id: "ht-1",
    room_type: "Executive Suite Ocean Front",
    price_per_night: 13500,
    available_count: 2,
    max_adults: 3,
    max_children: 2,
    features: ["Panoramic Ocean View", "Separate Living Room", "Bathtub", "Executive Lounge Access", "Free Breakfast"],
    images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80"],
  },
  {
    id: "rm-3",
    hotel_id: "ht-2",
    room_type: "Premium Tea Garden Suite",
    price_per_night: 6800,
    available_count: 4,
    max_adults: 2,
    max_children: 1,
    features: ["Mountain View Balcony", "King Size Bed", "Free Wifi", "Complimentary Breakfast"],
    images: ["https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80"],
  },
];

export const MOCK_HOTEL_REVIEWS: HotelReview[] = [
  {
    id: "rev-1",
    hotel_id: "ht-1",
    user_id: "usr-demo",
    user_name: "Tariqul Islam",
    rating: 5,
    comment: "Outstanding beach view from the balcony! Breakfast buffet had excellent Bangladeshi & continental items.",
    created_at: "2026-07-10T10:00:00Z",
  },
  {
    id: "rev-2",
    hotel_id: "ht-1",
    user_id: "usr-demo-2",
    user_name: "Farhana Yasmin",
    rating: 4,
    comment: "Very clean rooms, staff was extremely helpful with airport transfer.",
    created_at: "2026-06-25T14:30:00Z",
  },
];

export const MOCK_TOURS: Tour[] = [
  {
    id: "tr-1",
    title: "Cox's Bazar Beach & Inani Sunset Adventure",
    location: "Cox's Bazar, Bangladesh",
    duration_days: 3,
    price_per_person: 8500,
    currency: "BDT",
    category: "Domestic",
    discount: 12,
    rating: 4.9,
    reviews_count: 142,
    overview: "Explore the world's longest natural sea beach, marine drive, Himchari waterfall, and coral beaches of Inani.",
    description: "Join our signature Cox's Bazar weekend getaway! Enjoy 3 days of ocean waves, fresh seafood, sunrise at Sugandha beach, open-roof jeep ride along Marine Drive, and sunset at Inani Coral Beach.",
    inclusions: [
      "2 Nights Stay at 4-Star Ocean View Hotel",
      "Daily Buffet Breakfast & 1 Seafood BBQ Dinner",
      "Private AC Car Transfers for Sightseeing",
      "Marine Drive & Himchari Tour",
      "Dedicated Tour Guide",
    ],
    exclusions: ["Airfare / Bus ticket", "Personal shopping", "Water sports fee"],
    requirements: ["Valid NID or Student ID", "Sunscreen & Beachwear"],
    travel_tips: ["Best time for sunset photo is 5:30 PM at Inani", "Try local Rupchanda fry"],
    itinerary: [
      { day: 1, title: "Arrival & Beach Exploration", description: "Hotel check-in, lunch, and relax at Kolatoli beach for sunset." },
      { day: 2, title: "Marine Drive, Himchari & Inani", description: "Open Jeep ride to Himchari Hill, waterfall visit, and Inani coral beach sunset." },
      { day: 3, title: "Maheshkhali Island & Departure", description: "Speedboat ride to Adinath Temple Maheshkhali, souvenir shopping, and checkout." },
    ],
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
    ],
    attractions: ["Inani Coral Beach", "Marine Drive", "Himchari National Park"],
    activities: ["Jeep Safari", "Beach BBQ", "Speedboat Ride"],
    pickup_locations: ["Cox's Bazar Airport (CXB)", "Kolatoli Bus Terminal"],
    availability_dates: [
      { start_date: "2026-08-01", end_date: "2026-08-04" },
      { start_date: "2026-08-15", end_date: "2026-08-18" },
    ],
    max_group_size: 16,
    min_age: 3,
    cancellation_policy: "Free cancellation up to 72 hours before start date.",
    refund_policy: "80% refund if cancelled 48 hours prior.",
    latitude: 21.4272,
    longitude: 91.9704,
  },
  {
    id: "tr-2",
    title: "Sundarbans Wildlife Cruise & Royal Bengal Expedition",
    location: "Sundarbans, Khulna",
    duration_days: 4,
    price_per_person: 16500,
    currency: "BDT",
    category: "Adventure",
    discount: 10,
    rating: 4.8,
    reviews_count: 89,
    overview: "Cruise into the deep mangrove forest of UNESCO World Heritage Sundarbans on an executive tourist vessel.",
    description: "Immerse yourself in nature's wild kingdom. Spot Royal Bengal Tigers, saltwater crocodiles, spotted deer, and exotic birds.",
    inclusions: [
      "3 Nights Accommodation in Tourist Cruiser Cabin",
      "All meals onboard (Breakfast, Lunch, Snacks, Dinner)",
      "Forest Department Entry Permits & Armed Guards",
    ],
    exclusions: ["Transportation to Khulna / Mongla Port", "Camera permits"],
    requirements: ["NID/Passport Copy", "Mosquito repellent"],
    travel_tips: ["Wear muted clothing during forest walks"],
    itinerary: [
      { day: 1, title: "Embarkation at Mongla", description: "Board vessel, safety briefing, cruise towards Harbaria Eco Center." },
      { day: 2, title: "Katakal & Jamtola Beach Walk", description: "Canal rowing, tiger tracking walk to Jamtola virgin sea beach." },
      { day: 3, title: "Kotka Wildlife Sanctuary", description: "Observation tower visit, deer feeding, and evening BBQ." },
    ],
    images: ["https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80"],
    attractions: ["Kotka Wildlife Sanctuary", "Harbaria", "Jamtola Beach"],
    activities: ["Canal Cruise", "Forest Trekking"],
    pickup_locations: ["Mongla Port Jetty 1"],
    availability_dates: [{ start_date: "2026-09-10", end_date: "2026-09-14" }],
    max_group_size: 30,
    min_age: 6,
    cancellation_policy: "70% refund on vessel booking if cancelled 7 days prior.",
    refund_policy: "Partial refund as per forest regulations.",
    latitude: 21.9497,
    longitude: 89.1833,
  },
  {
    id: "tr-3",
    title: "Dubai Glamour & Desert Safari Extravaganza",
    location: "Dubai, United Arab Emirates",
    duration_days: 5,
    price_per_person: 68500,
    currency: "BDT",
    category: "International",
    discount: 8,
    rating: 4.95,
    reviews_count: 210,
    overview: "Experience the glittering skyline of Dubai, Burj Khalifa 124th Floor, Desert Safari BBQ, Dhow Cruise.",
    description: "Our bestseller international package! Includes visa assistance, 4-star hotel stay, dune bashing, and Marina Dhow cruise dinner.",
    inclusions: [
      "UAE Tourist Visa Processing Included",
      "4 Nights at 4-Star City Hotel",
      "Burj Khalifa 124th Floor Ticket",
      "4x4 Desert Safari & BBQ",
    ],
    exclusions: ["Airfare (Dhaka - Dubai - Dhaka)", "Personal shopping"],
    requirements: ["Passport valid 6+ months"],
    travel_tips: ["Dress modestly when visiting heritage sites"],
    itinerary: [
      { day: 1, title: "Arrival & Marina Dhow Cruise", description: "Airport pickup, hotel check-in, evening Marina Dhow Cruise dinner." },
      { day: 2, title: "Dubai City Tour & Burj Khalifa", description: "City tour covering Dubai Frame, Palm Jumeirah & Burj Khalifa." },
    ],
    images: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80"],
    attractions: ["Burj Khalifa", "Dubai Mall", "Desert Safari Camp"],
    activities: ["Dune Bashing", "Camel Riding"],
    pickup_locations: ["Dubai Intl Airport (DXB)"],
    availability_dates: [{ start_date: "2026-08-20", end_date: "2026-08-25" }],
    max_group_size: 20,
    min_age: 0,
    cancellation_policy: "80% refund 10 days before travel.",
    refund_policy: "Refund in 7 business days.",
    latitude: 25.2048,
    longitude: 55.2708,
  },
];

export const MOCK_VISAS: Visa[] = [
  {
    id: "vs-1",
    country: "Saudi Arabia (Umrah / Tourist)",
    country_code: "SA",
    flag_url: "https://flagcdn.com/w160/sa.png",
    visa_type: "E-Visa (1 Year Multiple Entry)",
    processing_time: "24 - 48 Hours",
    fee: 18500,
    currency: "BDT",
    add_on_services: [
      "Urgent Express Processing (12 Hours)",
      "Mandatory COVID & Health Insurance",
      "Biometric Appointment Assistance",
    ],
    important_notes: "Multiple entry valid for 1 year. Maximum 90 days stay per visit.",
    documents_required: {
      job_holders: ["Passport scan (Valid 6+ months)", "Photo white background", "NID copy", "Employer NOC"],
      business_owners: ["Passport scan", "Trade License with English translation", "Visiting Card & Letterhead"],
      students: ["Passport scan", "Student ID copy & Leave letter", "Parents Bank Statement"],
      others: ["Passport scan", "Personal Bank Statement 6 months (Min BDT 150k)", "Solvency Certificate"],
    },
    contact_info: {
      address_line1: "Isbah Travels Visa Hub, Suite 402, Gulshan Avenue, Dhaka 1212",
      hotline: "+880 1700-123456",
      email: "visa@isbahtravels.com",
    },
  },
  {
    id: "vs-2",
    country: "United Arab Emirates (Dubai)",
    country_code: "AE",
    flag_url: "https://flagcdn.com/w160/ae.png",
    visa_type: "30 Days Tourist E-Visa",
    processing_time: "3 - 5 Working Days",
    fee: 12500,
    currency: "BDT",
    add_on_services: ["OK to Board (OTB) Status", "Express 24-Hour Visa"],
    important_notes: "No embassy visit required. E-Visa issued directly as PDF.",
    documents_required: {
      job_holders: ["Color scan of Passport first & last page", "Recent photo white background", "NID copy"],
      business_owners: ["Passport color scan", "Trade License copy", "Visiting card"],
      students: ["Passport scan", "Student ID copy", "Parents NID copy"],
      others: ["Passport color scan", "Bank statement if requested"],
    },
    contact_info: {
      address_line1: "Isbah Travels Visa Hub, Suite 402, Gulshan Avenue, Dhaka 1212",
      hotline: "+880 1700-123456",
      email: "visa@isbahtravels.com",
    },
  },
  {
    id: "vs-3",
    country: "Thailand",
    country_code: "TH",
    flag_url: "https://flagcdn.com/w160/th.png",
    visa_type: "Single Entry Tourist Sticker Visa",
    processing_time: "5 - 7 Working Days",
    fee: 5800,
    currency: "BDT",
    add_on_services: ["VFS Application Submission", "Flight & Hotel Confirmation Voucher"],
    important_notes: "Bank statement must show closing balance of BDT 60,000 per person.",
    documents_required: {
      job_holders: ["Original Passport", "2 photos (3.5cm x 4.5cm)", "6 months Bank Statement & Solvency", "NOC"],
      business_owners: ["Original Passport", "Trade License (Notarized)", "Company Bank Statement"],
      students: ["Original Passport", "Student ID Copy & Leave letter", "Parents Financial Documents"],
      others: ["Original Passport", "Personal Bank Statement"],
    },
    contact_info: {
      address_line1: "Isbah Travels Visa Hub, Suite 402, Gulshan Avenue, Dhaka 1212",
      hotline: "+880 1700-123456",
      email: "visa@isbahtravels.com",
    },
  },
];

export const MOCK_BOOKINGS: Booking[] = [];

export const MOCK_SAVED_ITEMS: SavedItem[] = [];
